### ISSUE TITLE
update to 1.0.9

### ISSUE THREAD

**Issue by LuauDev** [Riz-ve/Xeno#52]
pwease

**Comment by Riz-ve** [comment]
![image](https://github.com/user-attachments/assets/440b1e31-af15-4e42-a2fa-f9b107bdce66)
![image](https://github.com/user-attachments/assets/012e0165-bbd1-46ed-bb3d-a5685a9434ee)

**Comment by Riz-ve** [comment]
you have copied my readme.md and this entire repository without leaving any credits

**Comment by maximusloltvink** [comment]
> > you have copied my readme.md and this entire repository without leaving any credits
> 
> die
> 
> edit: im sorry i should've credited you for your hard work i will credit u okay? please forgive me btw im skidder.lol on discord lmao

HAHAHAHAHA SO YOU ARE THAT STUPID DUDE WHO CAN'T CAN CODE ANYTHING AND JUST PASTES, GET OUT OF HERE YOU INTENSE

**Comment by LuauDev** [comment]
> > > you have copied my readme.md and this entire repository without leaving any credits
> > 
> > 
> > die
> > edit: im sorry i should've credited you for your hard work i will credit u okay? please forgive me btw im skidder.lol on discord lmao
> 
> HAHAHAHAHA SO YOU ARE THAT STUPID DUDE WHO CAN'T CAN CODE ANYTHING AND JUST PASTES, GET OUT OF HERE YOU INTENSE

my name is skidder, i can code, i have beef with most executors owners (kq, peak, qui, etc)
and i actually can code not like ur ass just fucking overhere, i literally updated code, added unc, fixed things, even made a fork named betterxeno, i updated xeno to 1.0.9

**Comment by maximusloltvink** [comment]
Me too, but I’m not trying to make ughh pastes that I then post on the Internet (as far as I know you do this) and try to doxx people who are guilty of almost nothing. As your friend told me, “run the source code of your cheat” otherwise your data will be leaked onto the Internet. what I didn't expect

**Comment by LuauDev** [comment]
> Me too, but I’m not trying to make ughh pastes that I then post on the Internet (as far as I know you do this) and try to doxx people who are guilty of almost nothing. As your friend told me, “run the source code of your cheat” otherwise your data will be leaked onto the Internet. what I didn't expect

nigga fix ur grammar and talk to me go learn some english lessons, nigga die
"me too" nigger i checked ur while profile in github and found no repo forked xeno or i xeno, u have 2 repos nigga

**Comment by maximusloltvink** [comment]
> > Me too, but I’m not trying to make ughh pastes that I then post on the Internet (as far as I know you do this) and try to doxx people who are guilty of almost nothing. As your friend told me, “run the source code of your cheat” otherwise your data will be leaked onto the Internet. what I didn't expect
> 
> nigga fix ur grammar and talk to me go learn some english lessons, nigga die "me too" nigger i checked ur while profile in github and found no repo forked xeno or i xeno, u have 2 repos nigga

I don't know English, what's wrong with that? and maybe you'll stop calling me a nigga? dude, you're going to sound like a 7 year old bro. but I don’t have forks since I often lose my github account, I could show the correspondence about how you tried to “dox” me and threatened me, child. You're acting like a brainless imbecile right now, honestly. although at the beginning of the conversation I also behaved aggressively.

**Comment by maximusloltvink** [comment]
and by run the source code cheat I meant DROP your SRC CODE or skidder.lol will receive your data. like you said YOU ALREADY RECEIVED MY DISCORD TOKEN and I just laughed.
